# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creport.proto\x12\rreportService\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n\x12ListReportsRequest\x12)\n\x06\x66ilter\x18\x01 \x01(\x0e\x32\x19.reportService.ReportType\x12\x0c\n\x04page\x18\x02 \x01(\x03\x12\x0c\n\x04size\x18\x03 \x01(\x03\"\x91\x01\n\x12ListReportResponse\x12\x12\n\ntotalCount\x18\x01 \x01(\x03\x12\x12\n\ntotalPages\x18\x02 \x01(\x03\x12\x0c\n\x04page\x18\x03 \x01(\x03\x12\x0c\n\x04size\x18\x04 \x01(\x03\x12\x0f\n\x07hasMore\x18\x05 \x01(\x08\x12&\n\x07reports\x18\x06 \x03(\x0b\x32\x15.reportService.Report\"\x93\x01\n\x06Report\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.reportService.ReportType\x12\r\n\x05topic\x18\x03 \x01(\t\x12\x30\n\x0c\x63reated_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0breport_data\x18\x05 \x01(\t*\"\n\nReportType\x12\x07\n\x03Job\x10\x00\x12\x0b\n\x07Unknown\x10\x01\x32\x66\n\rReportService\x12U\n\x0bListReports\x12!.reportService.ListReportsRequest\x1a!.reportService.ListReportResponse\"\x00\x42\x11Z\x0f.;reportServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'report_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017.;reportService'
  _globals['_REPORTTYPE']._serialized_start=455
  _globals['_REPORTTYPE']._serialized_end=489
  _globals['_LISTREPORTSREQUEST']._serialized_start=64
  _globals['_LISTREPORTSREQUEST']._serialized_end=155
  _globals['_LISTREPORTRESPONSE']._serialized_start=158
  _globals['_LISTREPORTRESPONSE']._serialized_end=303
  _globals['_REPORT']._serialized_start=306
  _globals['_REPORT']._serialized_end=453
  _globals['_REPORTSERVICE']._serialized_start=491
  _globals['_REPORTSERVICE']._serialized_end=593
# @@protoc_insertion_point(module_scope)
