FROM rust:1.70.0 AS base
ENV PROTOC_VERSION=23.3
ENV PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
RUN apt-get update && apt-get install -y unzip && apt-get install libpq-dev
RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/$PROTOC_ZIP \
    && unzip -o $PROTOC_ZIP -d /usr/local bin/protoc \
    && unzip -o $PROTOC_ZIP -d /usr/local 'include/*' \ 
    && rm -f $PROTOC_ZIP
RUN apt install -y netcat
RUN cargo install diesel_cli --no-default-features --features postgres

WORKDIR /usr/src/app
# Copy all files from the current directory of host to WORKDIR on container
COPY . .
# Build the Rust code inside the container
RUN cargo build --release

# Create a new image without the build tools
FROM rust:1.70.0

WORKDIR /usr/src/app
# copy only the compiled executable to the folder
COPY --from=base /usr/src/app/target/release/app .

CMD ["./app"]