FROM node:20.4.0

WORKDIR /usr/src/app

COPY ./client .

# Install app dependencies
RUN npm install
# Build the Next.js app
RUN npm run build
# Set the environment variable for Node.js production mode
ENV NODE_ENV=production

# Start the app
CMD ["npm", "start"]